export interface ExamPreset {
  id: string;
  name: string;
  exam: string;
  type: "photo" | "signature" | "thumb";
  width: number;
  height: number;
  minKB: number;
  maxKB: number;
  bgColor: string | null;
  format: "jpeg" | "png";
  dpi: number;
  requiresDateStamp: boolean;
  note: string;
  officialUrl: string;
  category: string;
  searchKeywords: string[];
}

export const CATEGORIES = [
  "SSC",
  "UPSC",
  "Banking",
  "Railway",
  "Medical/Engineering",
  "ID/Passport",
  "Postal",
  "State PSC",
  "Police",
  "Judiciary",
  "Custom",
] as const;

export const PRESETS: ExamPreset[] = [
  // ========== SSC ==========
  {
    id: "ssc-cgl-photo",
    name: "SSC CGL Photo",
    exam: "SSC CGL",
    type: "photo",
    width: 100,
    height: 120,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: true,
    note: "100x120px, 20-50KB, white bg",
    officialUrl: "https://ssc.gov.in",
    category: "SSC",
    searchKeywords: ["ssc cgl photo size", "ssc cgl photo resize", "ssc cgl photo 50kb"],
  },
  {
    id: "ssc-chsl-photo",
    name: "SSC CHSL Photo",
    exam: "SSC CHSL",
    type: "photo",
    width: 200,
    height: 240,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: true,
    note: "200x240px, 20-50KB, white bg",
    officialUrl: "https://ssc.gov.in",
    category: "SSC",
    searchKeywords: ["ssc chsl photo size", "ssc chsl photo resize", "ssc chsl photo 50kb"],
  },
  {
    id: "ssc-gd-photo",
    name: "SSC GD Photo",
    exam: "SSC GD",
    type: "photo",
    width: 200,
    height: 240,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: true,
    note: "200x240px, 20-50KB, white bg",
    officialUrl: "https://ssc.gov.in",
    category: "SSC",
    searchKeywords: ["ssc gd photo size", "ssc gd photo resize", "ssc gd constable photo"],
  },
  {
    id: "ssc-mts-photo",
    name: "SSC MTS Photo",
    exam: "SSC MTS",
    type: "photo",
    width: 200,
    height: 240,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: true,
    note: "200x240px, 20-50KB, white bg",
    officialUrl: "https://ssc.gov.in",
    category: "SSC",
    searchKeywords: ["ssc mts photo size", "ssc mts photo resize", "ssc mts photo 50kb"],
  },
  {
    id: "ssc-cgl-signature",
    name: "SSC CGL Signature",
    exam: "SSC CGL",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://ssc.gov.in",
    category: "SSC",
    searchKeywords: ["ssc cgl signature size", "ssc cgl signature resize", "ssc cgl signature 20kb"],
  },
  {
    id: "ssc-chsl-signature",
    name: "SSC CHSL Signature",
    exam: "SSC CHSL",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://ssc.gov.in",
    category: "SSC",
    searchKeywords: ["ssc chsl signature size", "ssc chsl signature resize", "ssc chsl signature 20kb"],
  },
  {
    id: "ssc-gd-signature",
    name: "SSC GD Signature",
    exam: "SSC GD",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://ssc.gov.in",
    category: "SSC",
    searchKeywords: ["ssc gd signature size", "ssc gd signature resize", "ssc gd signature 20kb"],
  },
  {
    id: "ssc-mts-signature",
    name: "SSC MTS Signature",
    exam: "SSC MTS",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://ssc.gov.in",
    category: "SSC",
    searchKeywords: ["ssc mts signature size", "ssc mts signature resize", "ssc mts signature 20kb"],
  },

  // ========== UPSC ==========
  {
    id: "upsc-photo",
    name: "UPSC Civil Services Photo",
    exam: "UPSC",
    type: "photo",
    width: 350,
    height: 350,
    minKB: 30,
    maxKB: 100,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "350x350px, 30-100KB, white bg (OTR registration)",
    officialUrl: "https://upsconline.nic.in",
    category: "UPSC",
    searchKeywords: ["upsc photo size", "upsc otr photo", "upsc 350x350"],
  },
  {
    id: "upsc-signature",
    name: "UPSC Signature",
    exam: "UPSC",
    type: "signature",
    width: 350,
    height: 150,
    minKB: 20,
    maxKB: 300,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "350x150px, 20-300KB",
    officialUrl: "https://upsconline.nic.in",
    category: "UPSC",
    searchKeywords: ["upsc signature size", "upsc signature resize"],
  },

  // ========== BANKING (IBPS/SBI) ==========
  {
    id: "ibps-sbi-photo",
    name: "IBPS/SBI Bank Exam Photo",
    exam: "IBPS/SBI",
    type: "photo",
    width: 200,
    height: 230,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x230px, 20-50KB, white bg",
    officialUrl: "https://ibps.in",
    category: "Banking",
    searchKeywords: ["ibps photo size", "sbi po photo resize", "bank exam photo 50kb"],
  },
  {
    id: "ibps-sbi-signature",
    name: "IBPS/SBI Signature",
    exam: "IBPS/SBI",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB, black ink on white",
    officialUrl: "https://ibps.in",
    category: "Banking",
    searchKeywords: ["ibps signature size", "sbi signature 20kb"],
  },
  {
    id: "ibps-sbi-thumb",
    name: "IBPS/SBI Left Thumb",
    exam: "IBPS/SBI",
    type: "thumb",
    width: 240,
    height: 240,
    minKB: 20,
    maxKB: 50,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "240x240px, 20-50KB",
    officialUrl: "https://ibps.in",
    category: "Banking",
    searchKeywords: ["ibps thumb impression size"],
  },
  {
    id: "sbi-po-photo",
    name: "SBI PO Photo",
    exam: "SBI PO",
    type: "photo",
    width: 200,
    height: 230,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x230px, 20-50KB, white bg",
    officialUrl: "https://sbi.co.in",
    category: "Banking",
    searchKeywords: ["sbi po photo size", "sbi po photo resize", "sbi po photo 50kb"],
  },
  {
    id: "sbi-po-signature",
    name: "SBI PO Signature",
    exam: "SBI PO",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://sbi.co.in",
    category: "Banking",
    searchKeywords: ["sbi po signature size", "sbi po signature resize"],
  },
  {
    id: "sbi-clerk-photo",
    name: "SBI Clerk Photo",
    exam: "SBI Clerk",
    type: "photo",
    width: 200,
    height: 230,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x230px, 20-50KB, white bg",
    officialUrl: "https://sbi.co.in",
    category: "Banking",
    searchKeywords: ["sbi clerk photo size", "sbi clerk photo resize", "sbi clerk photo 50kb"],
  },
  {
    id: "sbi-clerk-signature",
    name: "SBI Clerk Signature",
    exam: "SBI Clerk",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://sbi.co.in",
    category: "Banking",
    searchKeywords: ["sbi clerk signature size", "sbi clerk signature resize"],
  },
  {
    id: "rbi-grade-b-photo",
    name: "RBI Grade B Photo",
    exam: "RBI Grade B",
    type: "photo",
    width: 200,
    height: 230,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x230px, 20-50KB, white bg",
    officialUrl: "https://rbi.org.in",
    category: "Banking",
    searchKeywords: ["rbi grade b photo size", "rbi grade b photo resize", "rbi photo 50kb"],
  },
  {
    id: "rbi-grade-b-signature",
    name: "RBI Grade B Signature",
    exam: "RBI Grade B",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://rbi.org.in",
    category: "Banking",
    searchKeywords: ["rbi grade b signature size", "rbi grade b signature resize"],
  },
  {
    id: "sbi-cbo-photo",
    name: "SBI CBO Photo",
    exam: "SBI CBO",
    type: "photo",
    width: 200,
    height: 230,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x230px, 20-50KB, white bg",
    officialUrl: "https://sbi.co.in",
    category: "Banking",
    searchKeywords: ["sbi cbo photo size", "sbi cbo photo resize", "sbi cbo photo 50kb"],
  },
  {
    id: "sbi-cbo-signature",
    name: "SBI CBO Signature",
    exam: "SBI CBO",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://sbi.co.in",
    category: "Banking",
    searchKeywords: ["sbi cbo signature size", "sbi cbo signature resize"],
  },
  {
    id: "idbi-am-photo",
    name: "IDBI AM Photo",
    exam: "IDBI AM",
    type: "photo",
    width: 200,
    height: 230,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x230px, 20-50KB, white bg",
    officialUrl: "https://idbibank.in",
    category: "Banking",
    searchKeywords: ["idbi am photo size", "idbi am photo resize", "idbi bank photo"],
  },
  {
    id: "idbi-am-signature",
    name: "IDBI AM Signature",
    exam: "IDBI AM",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://idbibank.in",
    category: "Banking",
    searchKeywords: ["idbi am signature size", "idbi am signature resize"],
  },

  // ========== RAILWAY (RRB) ==========
  {
    id: "rrb-photo",
    name: "RRB Railway Photo",
    exam: "RRB",
    type: "photo",
    width: 350,
    height: 350,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: true,
    note: "3.5cm x 3.5cm (square), 20-50KB, white bg",
    officialUrl: "https://www.rrbcdg.gov.in",
    category: "Railway",
    searchKeywords: ["rrb photo size", "railway exam photo resize", "rrb group d photo"],
  },
  {
    id: "rrb-signature",
    name: "RRB Railway Signature",
    exam: "RRB",
    type: "signature",
    width: 350,
    height: 140,
    minKB: 20,
    maxKB: 50,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "5:2 ratio, 20-50KB",
    officialUrl: "https://www.rrbcdg.gov.in",
    category: "Railway",
    searchKeywords: ["rrb signature size", "railway signature 5:2 ratio"],
  },
  {
    id: "rrb-groupd-photo",
    name: "RRB Group D Photo",
    exam: "RRB Group D",
    type: "photo",
    width: 320,
    height: 240,
    minKB: 20,
    maxKB: 70,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "320x240px, 20-70KB, white bg",
    officialUrl: "https://www.rrbcdg.gov.in",
    category: "Railway",
    searchKeywords: ["rrb group d photo size"],
  },
  {
    id: "rrb-groupd-signature",
    name: "RRB Group D Signature",
    exam: "RRB Group D",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 30,
    maxKB: 70,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 30-70KB",
    officialUrl: "https://www.rrbcdg.gov.in",
    category: "Railway",
    searchKeywords: ["rrb group d signature size"],
  },
  {
    id: "rrb-alp-photo",
    name: "RRB ALP Photo",
    exam: "RRB ALP",
    type: "photo",
    width: 275,
    height: 354,
    minKB: 50,
    maxKB: 150,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "275x354px, 50-150KB, white bg",
    officialUrl: "https://www.rrbcdg.gov.in",
    category: "Railway",
    searchKeywords: ["rrb alp photo size", "rrb alp photo resize", "railway alp photo"],
  },
  {
    id: "rrb-alp-signature",
    name: "RRB ALP Signature",
    exam: "RRB ALP",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://www.rrbcdg.gov.in",
    category: "Railway",
    searchKeywords: ["rrb alp signature size", "rrb alp signature resize"],
  },

  // ========== MEDICAL/ENGINEERING ==========
  {
    id: "neet-photo",
    name: "NEET UG Photo",
    exam: "NEET",
    type: "photo",
    width: 276,
    height: 354,
    minKB: 10,
    maxKB: 200,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "Postcard ratio (3.5cm x 4.5cm), 10-200KB, white bg",
    officialUrl: "https://neet.nta.nic.in",
    category: "Medical/Engineering",
    searchKeywords: ["neet photo size", "neet ug photo resize", "neet postcard photo"],
  },
  {
    id: "neet-signature",
    name: "NEET Signature",
    exam: "NEET",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://neet.nta.nic.in",
    category: "Medical/Engineering",
    searchKeywords: ["neet signature size", "neet signature resize", "neet ug signature"],
  },
  {
    id: "jee-main-photo",
    name: "JEE Main Photo",
    exam: "JEE Main",
    type: "photo",
    width: 276,
    height: 354,
    minKB: 10,
    maxKB: 200,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "3.5cm x 4.5cm, 10-200KB, white bg",
    officialUrl: "https://jeemain.nta.ac.in",
    category: "Medical/Engineering",
    searchKeywords: ["jee main photo size", "jee photo resize"],
  },
  {
    id: "jee-main-signature",
    name: "JEE Main Signature",
    exam: "JEE Main",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://jeemain.nta.ac.in",
    category: "Medical/Engineering",
    searchKeywords: ["jee main signature size", "jee main signature resize", "jee signature"],
  },
  {
    id: "gate-photo",
    name: "GATE Photo",
    exam: "GATE",
    type: "photo",
    width: 350,
    height: 450,
    minKB: 5,
    maxKB: 1000,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "350x450px, 5-1000KB, white bg",
    officialUrl: "https://gate2026.iisc.ac.in",
    category: "Medical/Engineering",
    searchKeywords: ["gate photo size", "gate photo resize", "gate exam photo"],
  },
  {
    id: "gate-signature",
    name: "GATE Signature",
    exam: "GATE",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://gate2026.iisc.ac.in",
    category: "Medical/Engineering",
    searchKeywords: ["gate signature size", "gate signature resize", "gate exam signature"],
  },

  // ========== ID / PASSPORT ==========
  {
    id: "pan-card-photo",
    name: "PAN Card Photo (NSDL)",
    exam: "PAN Card",
    type: "photo",
    width: 132,
    height: 170,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "3.5cm x 2.5cm, 20-50KB, 200 DPI, white bg",
    officialUrl: "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
    category: "ID/Passport",
    searchKeywords: ["pan card photo size", "nsdl pan photo resize", "pan card photo 50kb"],
  },
  {
    id: "pan-card-signature",
    name: "PAN Card Signature (NSDL)",
    exam: "PAN Card",
    type: "signature",
    width: 170,
    height: 76,
    minKB: 10,
    maxKB: 50,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "2cm x 4.5cm, 10-50KB, 200 DPI",
    officialUrl: "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
    category: "ID/Passport",
    searchKeywords: ["pan card signature size", "nsdl signature resize"],
  },
  {
    id: "aadhaar-photo",
    name: "Aadhaar Card Photo",
    exam: "Aadhaar",
    type: "photo",
    width: 150,
    height: 200,
    minKB: 10,
    maxKB: 100,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "150x200px, 10-100KB, white bg",
    officialUrl: "https://uidai.gov.in",
    category: "ID/Passport",
    searchKeywords: ["aadhaar photo size", "aadhaar card photo resize"],
  },
  {
    id: "passport-india",
    name: "Indian Passport Photo",
    exam: "Passport",
    type: "photo",
    width: 413,
    height: 531,
    minKB: 20,
    maxKB: 300,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 300,
    requiresDateStamp: false,
    note: "2x2 inch (51x51mm), 20-300KB, white bg, 300 DPI",
    officialUrl: "https://portal2.passportindia.gov.in",
    category: "ID/Passport",
    searchKeywords: ["passport photo size india", "passport seva photo resize", "indian passport photo online"],
  },

  // ========== POSTAL ==========
  {
    id: "india-post-gds-photo",
    name: "India Post GDS Photo",
    exam: "India Post GDS",
    type: "photo",
    width: 200,
    height: 250,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "4:5 ratio, 200x250px, 20-50KB",
    officialUrl: "https://indiapostgdsonline.gov.in",
    category: "Postal",
    searchKeywords: ["india post gds photo size", "gds photo resize"],
  },
  {
    id: "india-post-gds-signature",
    name: "India Post GDS Signature",
    exam: "India Post GDS",
    type: "signature",
    width: 300,
    height: 120,
    minKB: 10,
    maxKB: 30,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "5:2 ratio, 10-30KB",
    officialUrl: "https://indiapostgdsonline.gov.in",
    category: "Postal",
    searchKeywords: ["gds signature size", "india post gds signature resize"],
  },

  // ========== STATE PSC ==========
  {
    id: "kerala-psc-photo",
    name: "Kerala PSC (Thulasi) Photo",
    exam: "Kerala PSC",
    type: "photo",
    width: 200,
    height: 150,
    minKB: 10,
    maxKB: 30,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x150px, under 30KB",
    officialUrl: "https://thulasi.psc.kerala.gov.in",
    category: "State PSC",
    searchKeywords: ["kerala psc photo size", "thulasi photo resize"],
  },
  {
    id: "kerala-psc-signature",
    name: "Kerala PSC (Thulasi) Signature",
    exam: "Kerala PSC",
    type: "signature",
    width: 100,
    height: 150,
    minKB: 10,
    maxKB: 30,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "100x150px, under 30KB",
    officialUrl: "https://thulasi.psc.kerala.gov.in",
    category: "State PSC",
    searchKeywords: ["kerala psc signature size", "thulasi signature resize"],
  },
  {
    id: "bpsc-photo",
    name: "BPSC Photo",
    exam: "BPSC",
    type: "photo",
    width: 250,
    height: 250,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "250x250px, 20-50KB, white bg",
    officialUrl: "https://bpsc.bih.nic.in",
    category: "State PSC",
    searchKeywords: ["bpsc photo size", "bpsc photo resize", "bihar psc photo"],
  },
  {
    id: "bpsc-signature",
    name: "BPSC Signature",
    exam: "BPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://bpsc.bih.nic.in",
    category: "State PSC",
    searchKeywords: ["bpsc signature size", "bpsc signature resize"],
  },
  {
    id: "uppsc-photo",
    name: "UPPSC Photo",
    exam: "UPPSC",
    type: "photo",
    width: 180,
    height: 216,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "180x216px, 20-50KB, white bg",
    officialUrl: "https://uppsc.up.nic.in",
    category: "State PSC",
    searchKeywords: ["uppsc photo size", "uppsc photo resize", "up psc photo"],
  },
  {
    id: "uppsc-signature",
    name: "UPPSC Signature",
    exam: "UPPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://uppsc.up.nic.in",
    category: "State PSC",
    searchKeywords: ["uppsc signature size", "uppsc signature resize"],
  },
  {
    id: "mpsc-photo",
    name: "MPSC Photo",
    exam: "MPSC",
    type: "photo",
    width: 276,
    height: 354,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "276x354px, 20-50KB, white bg",
    officialUrl: "https://mpsc.gov.in",
    category: "State PSC",
    searchKeywords: ["mpsc photo size", "mpsc photo resize", "maharashtra psc photo"],
  },
  {
    id: "mpsc-signature",
    name: "MPSC Signature",
    exam: "MPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://mpsc.gov.in",
    category: "State PSC",
    searchKeywords: ["mpsc signature size", "mpsc signature resize"],
  },
  {
    id: "tnpsc-photo",
    name: "TNPSC Photo",
    exam: "TNPSC",
    type: "photo",
    width: 275,
    height: 354,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "275x354px, 20-50KB, white bg",
    officialUrl: "https://tnpsc.gov.in",
    category: "State PSC",
    searchKeywords: ["tnpsc photo size", "tnpsc photo resize", "tamil nadu psc photo"],
  },
  {
    id: "tnpsc-signature",
    name: "TNPSC Signature",
    exam: "TNPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://tnpsc.gov.in",
    category: "State PSC",
    searchKeywords: ["tnpsc signature size", "tnpsc signature resize"],
  },
  {
    id: "wbcs-photo",
    name: "WBCS Photo",
    exam: "WBCS",
    type: "photo",
    width: 138,
    height: 177,
    minKB: 20,
    maxKB: 100,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "138x177px, 20-100KB, white bg",
    officialUrl: "https://wbpsc.gov.in",
    category: "State PSC",
    searchKeywords: ["wbcs photo size", "wbcs photo resize", "west bengal psc photo"],
  },
  {
    id: "wbcs-signature",
    name: "WBCS Signature",
    exam: "WBCS",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://wbpsc.gov.in",
    category: "State PSC",
    searchKeywords: ["wbcs signature size", "wbcs signature resize"],
  },
  {
    id: "gpsc-photo",
    name: "GPSC Photo",
    exam: "GPSC",
    type: "photo",
    width: 130,
    height: 180,
    minKB: 10,
    maxKB: 15,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "130x180px, 10-15KB, white bg",
    officialUrl: "https://gpsc.gujarat.gov.in",
    category: "State PSC",
    searchKeywords: ["gpsc photo size", "gpsc photo resize", "gujarat psc photo"],
  },
  {
    id: "gpsc-signature",
    name: "GPSC Signature",
    exam: "GPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://gpsc.gujarat.gov.in",
    category: "State PSC",
    searchKeywords: ["gpsc signature size", "gpsc signature resize"],
  },
  {
    id: "rpsc-photo",
    name: "RPSC Photo",
    exam: "RPSC",
    type: "photo",
    width: 240,
    height: 320,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "240x320px, 20-50KB, white bg",
    officialUrl: "https://rpsc.rajasthan.gov.in",
    category: "State PSC",
    searchKeywords: ["rpsc photo size", "rpsc photo resize", "rajasthan psc photo"],
  },
  {
    id: "rpsc-signature",
    name: "RPSC Signature",
    exam: "RPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://rpsc.rajasthan.gov.in",
    category: "State PSC",
    searchKeywords: ["rpsc signature size", "rpsc signature resize"],
  },
  {
    id: "hpsc-photo",
    name: "HPSC Photo",
    exam: "HPSC",
    type: "photo",
    width: 138,
    height: 177,
    minKB: 10,
    maxKB: 100,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "138x177px, 10-100KB, white bg",
    officialUrl: "https://hpsc.gov.in",
    category: "State PSC",
    searchKeywords: ["hpsc photo size", "hpsc photo resize", "haryana psc photo"],
  },
  {
    id: "hpsc-signature",
    name: "HPSC Signature",
    exam: "HPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://hpsc.gov.in",
    category: "State PSC",
    searchKeywords: ["hpsc signature size", "hpsc signature resize"],
  },
  {
    id: "tspsc-photo",
    name: "TSPSC Photo",
    exam: "TSPSC",
    type: "photo",
    width: 275,
    height: 354,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "275x354px, 20-50KB, white bg",
    officialUrl: "https://tspsc.gov.in",
    category: "State PSC",
    searchKeywords: ["tspsc photo size", "tspsc photo resize", "telangana psc photo"],
  },
  {
    id: "tspsc-signature",
    name: "TSPSC Signature",
    exam: "TSPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://tspsc.gov.in",
    category: "State PSC",
    searchKeywords: ["tspsc signature size", "tspsc signature resize"],
  },
  {
    id: "cgpsc-photo",
    name: "CGPSC Photo",
    exam: "CGPSC",
    type: "photo",
    width: 275,
    height: 354,
    minKB: 30,
    maxKB: 100,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "275x354px, 30-100KB, white bg",
    officialUrl: "https://psc.cg.gov.in",
    category: "State PSC",
    searchKeywords: ["cgpsc photo size", "cgpsc photo resize", "chhattisgarh psc photo"],
  },
  {
    id: "cgpsc-signature",
    name: "CGPSC Signature",
    exam: "CGPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://psc.cg.gov.in",
    category: "State PSC",
    searchKeywords: ["cgpsc signature size", "cgpsc signature resize"],
  },
  {
    id: "ukpsc-photo",
    name: "UKPSC Photo",
    exam: "UKPSC",
    type: "photo",
    width: 150,
    height: 200,
    minKB: 30,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "150x200px, 30-50KB, white bg",
    officialUrl: "https://ukpsc.gov.in",
    category: "State PSC",
    searchKeywords: ["ukpsc photo size", "ukpsc photo resize", "uttarakhand psc photo"],
  },
  {
    id: "ukpsc-signature",
    name: "UKPSC Signature",
    exam: "UKPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://ukpsc.gov.in",
    category: "State PSC",
    searchKeywords: ["ukpsc signature size", "ukpsc signature resize"],
  },
  {
    id: "appsc-photo",
    name: "APPSC Photo",
    exam: "APPSC",
    type: "photo",
    width: 200,
    height: 250,
    minKB: 50,
    maxKB: 100,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x250px, 50-100KB, white bg",
    officialUrl: "https://psc.ap.gov.in",
    category: "State PSC",
    searchKeywords: ["appsc photo size", "appsc photo resize", "andhra pradesh psc photo"],
  },
  {
    id: "appsc-signature",
    name: "APPSC Signature",
    exam: "APPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://psc.ap.gov.in",
    category: "State PSC",
    searchKeywords: ["appsc signature size", "appsc signature resize"],
  },
  {
    id: "jpsc-photo",
    name: "JPSC Photo",
    exam: "JPSC",
    type: "photo",
    width: 200,
    height: 230,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x230px, 20-50KB, white bg",
    officialUrl: "https://jpsc.gov.in",
    category: "State PSC",
    searchKeywords: ["jpsc photo size", "jpsc photo resize", "jharkhand psc photo"],
  },
  {
    id: "jpsc-signature",
    name: "JPSC Signature",
    exam: "JPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://jpsc.gov.in",
    category: "State PSC",
    searchKeywords: ["jpsc signature size", "jpsc signature resize"],
  },
  {
    id: "mppsc-photo",
    name: "MPPSC Photo",
    exam: "MPPSC",
    type: "photo",
    width: 276,
    height: 354,
    minKB: 25,
    maxKB: 200,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "276x354px, 25-200KB, white bg",
    officialUrl: "https://mppsc.mp.gov.in",
    category: "State PSC",
    searchKeywords: ["mppsc photo size", "mppsc photo resize", "madhya pradesh psc photo"],
  },
  {
    id: "mppsc-signature",
    name: "MPPSC Signature",
    exam: "MPPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://mppsc.mp.gov.in",
    category: "State PSC",
    searchKeywords: ["mppsc signature size", "mppsc signature resize"],
  },
  {
    id: "opsc-photo",
    name: "OPSC Photo",
    exam: "OPSC",
    type: "photo",
    width: 200,
    height: 230,
    minKB: 20,
    maxKB: 100,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x230px, 20-100KB, white bg",
    officialUrl: "https://opsc.gov.in",
    category: "State PSC",
    searchKeywords: ["opsc photo size", "opsc photo resize", "odisha psc photo"],
  },
  {
    id: "opsc-signature",
    name: "OPSC Signature",
    exam: "OPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://opsc.gov.in",
    category: "State PSC",
    searchKeywords: ["opsc signature size", "opsc signature resize"],
  },
  {
    id: "apsc-assam-photo",
    name: "APSC Photo",
    exam: "APSC",
    type: "photo",
    width: 276,
    height: 354,
    minKB: 50,
    maxKB: 200,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "276x354px, 50-200KB, white bg",
    officialUrl: "https://apsc.nic.in",
    category: "State PSC",
    searchKeywords: ["apsc photo size", "apsc photo resize", "assam psc photo"],
  },
  {
    id: "apsc-assam-signature",
    name: "APSC Signature",
    exam: "APSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://apsc.nic.in",
    category: "State PSC",
    searchKeywords: ["apsc signature size", "apsc signature resize"],
  },
  {
    id: "ppsc-photo",
    name: "PPSC Photo",
    exam: "PPSC",
    type: "photo",
    width: 140,
    height: 177,
    minKB: 10,
    maxKB: 40,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x177px, 10-40KB, white bg",
    officialUrl: "https://ppsc.gov.in",
    category: "State PSC",
    searchKeywords: ["ppsc photo size", "ppsc photo resize", "punjab psc photo"],
  },
  {
    id: "ppsc-signature",
    name: "PPSC Signature",
    exam: "PPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://ppsc.gov.in",
    category: "State PSC",
    searchKeywords: ["ppsc signature size", "ppsc signature resize"],
  },
  {
    id: "hppsc-photo",
    name: "HPPSC Photo",
    exam: "HPPSC",
    type: "photo",
    width: 110,
    height: 140,
    minKB: 10,
    maxKB: 40,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "110x140px, 10-40KB, white bg",
    officialUrl: "https://hppsc.hp.gov.in",
    category: "State PSC",
    searchKeywords: ["hppsc photo size", "hppsc photo resize", "himachal psc photo"],
  },
  {
    id: "hppsc-signature",
    name: "HPPSC Signature",
    exam: "HPPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://hppsc.hp.gov.in",
    category: "State PSC",
    searchKeywords: ["hppsc signature size", "hppsc signature resize"],
  },
  {
    id: "jkpsc-photo",
    name: "JKPSC Photo",
    exam: "JKPSC",
    type: "photo",
    width: 200,
    height: 240,
    minKB: 10,
    maxKB: 20,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x240px, 10-20KB, white bg",
    officialUrl: "https://jkpsc.nic.in",
    category: "State PSC",
    searchKeywords: ["jkpsc photo size", "jkpsc photo resize", "j&k psc photo"],
  },
  {
    id: "jkpsc-signature",
    name: "JKPSC Signature",
    exam: "JKPSC",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://jkpsc.nic.in",
    category: "State PSC",
    searchKeywords: ["jkpsc signature size", "jkpsc signature resize"],
  },
  {
    id: "jkssb-photo",
    name: "JKSSB Photo",
    exam: "JKSSB",
    type: "photo",
    width: 180,
    height: 225,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "180x225px, 20-50KB, white bg",
    officialUrl: "https://jkssb.nic.in",
    category: "State PSC",
    searchKeywords: ["jkssb photo size", "jkssb photo resize", "j&k ssb photo"],
  },
  {
    id: "jkssb-signature",
    name: "JKSSB Signature",
    exam: "JKSSB",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://jkssb.nic.in",
    category: "State PSC",
    searchKeywords: ["jkssb signature size", "jkssb signature resize"],
  },

  // ========== POLICE ==========
  {
    id: "delhi-police-photo",
    name: "Delhi Police Photo",
    exam: "Delhi Police",
    type: "photo",
    width: 100,
    height: 120,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "100x120px, 20-50KB, white bg",
    officialUrl: "https://delhipolice.gov.in",
    category: "Police",
    searchKeywords: ["delhi police photo size", "delhi police photo resize", "delhi police constable photo"],
  },
  {
    id: "delhi-police-signature",
    name: "Delhi Police Signature",
    exam: "Delhi Police",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://delhipolice.gov.in",
    category: "Police",
    searchKeywords: ["delhi police signature size", "delhi police signature resize"],
  },
  {
    id: "up-police-photo",
    name: "UP Police Photo",
    exam: "UP Police",
    type: "photo",
    width: 180,
    height: 225,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "180x225px, 20-50KB, white bg",
    officialUrl: "https://uppbpb.gov.in",
    category: "Police",
    searchKeywords: ["up police photo size", "up police photo resize", "up police constable photo"],
  },
  {
    id: "up-police-signature",
    name: "UP Police Signature",
    exam: "UP Police",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://uppbpb.gov.in",
    category: "Police",
    searchKeywords: ["up police signature size", "up police signature resize"],
  },
  {
    id: "punjab-police-photo",
    name: "Punjab Police Photo",
    exam: "Punjab Police",
    type: "photo",
    width: 200,
    height: 240,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x240px, 20-50KB, white bg",
    officialUrl: "https://punjabpolice.gov.in",
    category: "Police",
    searchKeywords: ["punjab police photo size", "punjab police photo resize", "punjab police recruitment photo"],
  },
  {
    id: "punjab-police-signature",
    name: "Punjab Police Signature",
    exam: "Punjab Police",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://punjabpolice.gov.in",
    category: "Police",
    searchKeywords: ["punjab police signature size", "punjab police signature resize"],
  },
  {
    id: "wb-police-photo",
    name: "WB Police Photo",
    exam: "WB Police",
    type: "photo",
    width: 200,
    height: 240,
    minKB: 10,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x240px, 10-50KB, white bg",
    officialUrl: "https://wbpolice.gov.in",
    category: "Police",
    searchKeywords: ["wb police photo size", "wb police photo resize", "west bengal police photo"],
  },
  {
    id: "wb-police-signature",
    name: "WB Police Signature",
    exam: "WB Police",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://wbpolice.gov.in",
    category: "Police",
    searchKeywords: ["wb police signature size", "wb police signature resize"],
  },
  {
    id: "haryana-police-photo",
    name: "Haryana Police Photo",
    exam: "Haryana Police",
    type: "photo",
    width: 138,
    height: 177,
    minKB: 20,
    maxKB: 40,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "138x177px, 20-40KB, white bg",
    officialUrl: "https://hssc.gov.in",
    category: "Police",
    searchKeywords: ["haryana police photo size", "haryana police photo resize", "hssc police photo"],
  },
  {
    id: "haryana-police-signature",
    name: "Haryana Police Signature",
    exam: "Haryana Police",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://hssc.gov.in",
    category: "Police",
    searchKeywords: ["haryana police signature size", "haryana police signature resize"],
  },
  {
    id: "rajasthan-police-photo",
    name: "Rajasthan Police Photo",
    exam: "Rajasthan Police",
    type: "photo",
    width: 350,
    height: 450,
    minKB: 50,
    maxKB: 100,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "350x450px, 50-100KB, white bg",
    officialUrl: "https://police.rajasthan.gov.in",
    category: "Police",
    searchKeywords: ["rajasthan police photo size", "rajasthan police photo resize", "rajasthan police constable photo"],
  },
  {
    id: "rajasthan-police-signature",
    name: "Rajasthan Police Signature",
    exam: "Rajasthan Police",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://police.rajasthan.gov.in",
    category: "Police",
    searchKeywords: ["rajasthan police signature size", "rajasthan police signature resize"],
  },
  {
    id: "maharashtra-police-photo",
    name: "Maharashtra Police Photo",
    exam: "Maharashtra Police",
    type: "photo",
    width: 160,
    height: 200,
    minKB: 5,
    maxKB: 20,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "160x200px, 5-20KB, white bg",
    officialUrl: "https://mahapolice.gov.in",
    category: "Police",
    searchKeywords: ["maharashtra police photo size", "maharashtra police photo resize", "maha police photo"],
  },
  {
    id: "maharashtra-police-signature",
    name: "Maharashtra Police Signature",
    exam: "Maharashtra Police",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://mahapolice.gov.in",
    category: "Police",
    searchKeywords: ["maharashtra police signature size", "maharashtra police signature resize"],
  },
  {
    id: "tn-police-photo",
    name: "TN Police Photo",
    exam: "TN Police",
    type: "photo",
    width: 275,
    height: 354,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "275x354px, 20-50KB, white bg",
    officialUrl: "https://tnusrb.tn.gov.in",
    category: "Police",
    searchKeywords: ["tn police photo size", "tn police photo resize", "tamil nadu police photo"],
  },
  {
    id: "tn-police-signature",
    name: "TN Police Signature",
    exam: "TN Police",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://tnusrb.tn.gov.in",
    category: "Police",
    searchKeywords: ["tn police signature size", "tn police signature resize"],
  },
  {
    id: "kerala-police-recruit-photo",
    name: "Kerala Police Photo",
    exam: "Kerala Police",
    type: "photo",
    width: 150,
    height: 200,
    minKB: 20,
    maxKB: 30,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "150x200px, 20-30KB, white bg",
    officialUrl: "https://keralapolice.gov.in",
    category: "Police",
    searchKeywords: ["kerala police photo size", "kerala police photo resize", "kerala police recruitment photo"],
  },
  {
    id: "kerala-police-recruit-signature",
    name: "Kerala Police Signature",
    exam: "Kerala Police",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://keralapolice.gov.in",
    category: "Police",
    searchKeywords: ["kerala police signature size", "kerala police signature resize"],
  },
  {
    id: "bihar-police-photo",
    name: "Bihar Police Photo",
    exam: "Bihar Police",
    type: "photo",
    width: 200,
    height: 230,
    minKB: 30,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x230px, 30-50KB, white bg",
    officialUrl: "https://bpssc.bih.nic.in",
    category: "Police",
    searchKeywords: ["bihar police photo size", "bihar police photo resize", "bpssc photo"],
  },
  {
    id: "bihar-police-signature",
    name: "Bihar Police Signature",
    exam: "Bihar Police",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://bpssc.bih.nic.in",
    category: "Police",
    searchKeywords: ["bihar police signature size", "bihar police signature resize"],
  },
  {
    id: "mp-police-photo",
    name: "MP Police Photo",
    exam: "MP Police",
    type: "photo",
    width: 200,
    height: 250,
    minKB: 50,
    maxKB: 200,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x250px, 50-200KB, white bg",
    officialUrl: "https://mppolice.gov.in",
    category: "Police",
    searchKeywords: ["mp police photo size", "mp police photo resize", "madhya pradesh police photo"],
  },
  {
    id: "mp-police-signature",
    name: "MP Police Signature",
    exam: "MP Police",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://mppolice.gov.in",
    category: "Police",
    searchKeywords: ["mp police signature size", "mp police signature resize"],
  },
  {
    id: "karnataka-police-photo",
    name: "Karnataka Police Photo",
    exam: "Karnataka Police",
    type: "photo",
    width: 200,
    height: 250,
    minKB: 30,
    maxKB: 100,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x250px, 30-100KB, white bg",
    officialUrl: "https://ksp.karnataka.gov.in",
    category: "Police",
    searchKeywords: ["karnataka police photo size", "karnataka police photo resize", "ksp photo"],
  },
  {
    id: "karnataka-police-signature",
    name: "Karnataka Police Signature",
    exam: "Karnataka Police",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://ksp.karnataka.gov.in",
    category: "Police",
    searchKeywords: ["karnataka police signature size", "karnataka police signature resize"],
  },

  // ========== JUDICIARY ==========
  {
    id: "djs-photo",
    name: "Delhi Judicial Service Photo",
    exam: "Delhi Judicial Service",
    type: "photo",
    width: 200,
    height: 240,
    minKB: 20,
    maxKB: 50,
    bgColor: "#FFFFFF",
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "200x240px, 20-50KB, white bg",
    officialUrl: "https://delhihighcourt.nic.in",
    category: "Judiciary",
    searchKeywords: ["djs photo size", "delhi judicial service photo", "djs photo resize"],
  },
  {
    id: "djs-signature",
    name: "Delhi Judicial Service Signature",
    exam: "Delhi Judicial Service",
    type: "signature",
    width: 140,
    height: 60,
    minKB: 10,
    maxKB: 20,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "140x60px, 10-20KB",
    officialUrl: "https://delhihighcourt.nic.in",
    category: "Judiciary",
    searchKeywords: ["djs signature size", "delhi judicial service signature", "djs signature resize"],
  },

  // ========== CUSTOM ==========
  {
    id: "custom",
    name: "Custom Size",
    exam: "Custom",
    type: "photo",
    width: 200,
    height: 200,
    minKB: 10,
    maxKB: 100,
    bgColor: null,
    format: "jpeg",
    dpi: 200,
    requiresDateStamp: false,
    note: "Enter your own dimensions and KB range",
    officialUrl: "",
    category: "Custom",
    searchKeywords: ["custom photo resize", "resize image to kb"],
  },
];

export function getPresetById(id: string): ExamPreset | undefined {
  return PRESETS.find(p => p.id === id);
}

export function getPresetsByCategory(category: string): ExamPreset[] {
  return PRESETS.filter(p => p.category === category);
}

export function getPresetSlug(preset: ExamPreset): string {
  if (preset.type === "photo") {
    return `${preset.id.replace(/-photo$/, "")}-photo-resizer`;
  } else if (preset.type === "signature") {
    return `${preset.id.replace(/-signature$/, "")}-signature-resizer`;
  }
  return `${preset.id}-resizer`;
}
